feat: obtain repository settings file
artipie/front pull request #15
Opened 2022-02-18 14:14 UTC by olenagerasimova

Part of #5 
Created `RepoSettings` to hide all the logic with flat/org layout and yaml/yml extension while searching for repository settings file by its name. Also:
- added runtime `NotFoundException` and corresponding handler for it
- simplified `GetRepository` class to use new `RepoSettings` class
- added method to get attribute name into `RequestAttr.Standard`

2022-02-18 15:09 UTC, g4s8 requested changes
@olenagerasimova just minor comment

2022-02-21 06:16 UTC, olenagerasimova commented on src/main/java/com/artipie/front/RequestAttr.java
> +        public String attrName() {
Enums already have final method `name()` to return item names, so I cannot rename this method(

2022-02-21 06:17 UTC, olenagerasimova commented
@g4s8 answered and fixed checkstyle after merging master, take a look please

2022-02-21 08:27 UTC, g4s8 approved these changes
@olenagerasimova ok, thanks

2022-02-21 08:27 UTC, merged