feat: check if repository exists
artipie/front pull request #17
Opened 2022-02-21 09:20 UTC by olenagerasimova

Part of #5 
Added endpoint to handle repository head request, extracted method in `RepoSettings` to get repo settings key, added default `RequestAttr.readOrThrow()` method to obtain required request attribute or throw exception.

2022-02-21 15:18 UTC, g4s8 requested changes
@olenagerasimova just one comment

2022-02-21 15:18 UTC, g4s8 commented on src/main/java/com/artipie/front/api/HeadRepository.java
> +        return "OK";
For `HEAD` requests we don't need to return any body

2022-02-22 06:46 UTC, olenagerasimova commented
@g4s8 thanks, corrected

2022-02-22 10:35 UTC, g4s8 approved these changes
@olenagerasimova thanks

2022-02-22 10:35 UTC, merged