feat: get users list
artipie/front pull request #18
Opened 2022-02-21 11:22 UTC by olenagerasimova

Part of #5 
Implemented endpoint to get users list. As we have 3 auth type (from file, env or github) response consists of three sections:
`file` lists all users from credentials file, `env` provides user name set in env and `github` section shows whether github auth is enabled.

```json
{ "file": 
  {
    "Alice": {"email":"alice@example.com"},
    "John": {"groups":["reader","dev-lead"]}
  },
  "env": {"Jane":{}},
  "github": {"enabled":false}
}
```

2022-02-22 10:59 UTC, g4s8 requested changes
@olenagerasimova I'm not sure about the format of `/users` response: I think we need to hide implementation details about authentication methods and just return user list without specifying the source of these users (maybe we need another API for authentication's mechanisms, e.g. to enable or disable some particular authentication method). So I'm suggesting to keep current user list but moving to root of document and removing other auth-options configuration:
```json
  {
    "Alice": {"email":"alice@example.com"},
    "John": {"groups":["reader","dev-lead"]}
  }
```

2022-02-22 11:05 UTC, olenagerasimova commented
@g4s8 ok, what about user from env auth (if it's enabled)? Should I add it to the list?

2022-02-22 12:07 UTC, g4s8 commented
> @g4s8 ok, what about user from env auth (if it's enabled)? Should I add it to the list?

@olenagerasimova environment variables are also just authentication method, user can be authenticated but don't have any permissions, so we need to add this user to any group either case. So no need to list environment logins here

2022-02-22 14:12 UTC, olenagerasimova commented
> @olenagerasimova environment variables are also just authentication method, user can be authenticated but don't have any permissions, so we need to add this user to any group either case. So no need to list environment logins here

That is not quite correct: user from env variables is the same as user from credentials file (`email` and `groups` in this file are not required) and can have various permissions to various repositories (as permissions to access repository are set in repository settings file).

2022-02-24 05:48 UTC, olenagerasimova commented
@g4s8 corrected, take a look, please

2022-02-24 06:19 UTC, g4s8 requested changes
@olenagerasimova thanks, looks good, just one comment about unit-test

2022-02-24 06:19 UTC, g4s8 commented on src/test/java/com/artipie/front/api/UsersTest.java
> +                Yaml.createYamlMappingBuilder().add(
You can reuse classes from https://github.com/artipie/front/blob/master/src/test/java/com/artipie/front/settings/YamlCredentialsTest.java to build credentials (or maybe extract it to some test package)

2022-02-24 06:38 UTC, olenagerasimova commented
@g4s8 thanks, corrected

2022-02-24 09:02 UTC, g4s8 approved these changes
@olenagerasimova thanks

2022-02-24 09:03 UTC, merged